spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: -1
    docExpansion: none
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    git:
      mode: full
    build:
      enabled: true
    env:
      enabled: true
info:
  app:
    name: GHKG APP
    description: APP with API for testing purpose - GHolak and KGomulski
